# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('downPay', models.DecimalField(decimal_places=2, max_digits=15)),
                ('intRate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mortTerm', models.IntegerField()),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=15)),
                ('insurance', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houserepo.Details')),
            ],
        ),
    ]
